# Generated by Django 3.2.3 on 2021-05-19 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nomClient', models.CharField(max_length=50)),
                ('telClient', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('dureeTotal', models.IntegerField()),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdr.client')),
            ],
        ),
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('duree', models.IntegerField()),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdr.client')),
            ],
        ),
    ]
